=pod

=head1 Name

Forward::Routes

=head1 Description

L<Forward::Routes>: routes for framework builders, experimental, so API might change

=head1 Author

ForwardEver

=head1 Copyright and License

Copyright (C) 2011, ForwardEver

This program is free software, you can redistribute it and/or modify it under
the terms of the Artistic License version 2.0.

=head1 Credits

Path matching and path building inspired by Viacheslav Tykhanovskyi's Router module L<https://github.com/vti/router>

Concept of nested routes inspired by Sebastian Riedel's Mojolicious::Routes module L<https://github.com/kraih/mojo/tree/master/lib/Mojolicious/Routes>

Concept of restful resources inspired by Ruby on Rails

=cut
